// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package router

import (
	"bookstack/repository"
	"bookstack/router/v3"
	"gorm.io/gorm"
)

// Injectors from router_wire.go:

func newRouter(db *gorm.DB, repo repository.Repository) *Router {
	echo := newEcho(repo)
	handlers := &v3.Handlers{
		Repo: repo,
	}
	router := &Router{
		e:  echo,
		v3: handlers,
	}
	return router
}
